# https://docs.blender.org/manual/en/dev/advanced/extensions/index.html
schema_version = "1.0.0"
id = "blender_clipping_assistant"
name = "Clipping Assistant"
version = "2.2.0"
tagline = "Assistant to set Viewport and Camera Clipping Distance"
maintainer = "Daniel Grauer (kromar)"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://superhivemarket.com/products/clipping-assistant"
copyright = ["2024 Daniel Grauer (kromar)"]
[build] 
  paths_exclude_pattern = [
  ".git", 
  "__pycache__/", 
  ".gitignore", 
  "README.md", 
  "LICENSE.md",
  "*.psd", "*.kra", "*.xpm", "*.blend",
  "build", 
  ]
